### ISSUE TITLE
The registration link is broken

### ISSUE THREAD

**Issue by WoBuGs** [open-source-dfir/slack#3]
As explained in the title, the registration link is broken :(

**Comment by joachimmetz** [comment]
Thx for flagging @berggren any insight into why the link is no longer working?

**Comment by beeporb** [comment]
Tagging on this as I was looking to join. Was it hosted on Heroku free tier? I know they binned that pretty recently.

**Comment by zbetcheckin** [comment]
Registration link still broken. Interested in to join.

![a](https://user-images.githubusercontent.com/10907782/228914740-25dea369-8bc9-4bfa-adb0-b841ff301166.png)

**Comment by joachimmetz** [comment]
Since Slack requires an invite via email, send a request with name, email address and little bit of background information to open-source-dfir-signup@googlegroups.com

**Comment by joachimmetz** [comment]
Switching to manual email group for now
